[build]
  # Build command with ESLint disabled for production
  command = "DISABLE_ESLINT_PLUGIN=true npm run build"

  # Directory to publish (React build output)
  publish = "build"

# SPA (Single Page Application) redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set in Netlify UI)
# REACT_APP_FIREBASE_API_KEY
# REACT_APP_FIREBASE_AUTH_DOMAIN
# REACT_APP_FIREBASE_PROJECT_ID
# REACT_APP_FIREBASE_STORAGE_BUCKET
# REACT_APP_FIREBASE_MESSAGING_SENDER_ID
# REACT_APP_FIREBASE_APP_ID

# Functions (if using Netlify functions)
[functions]
  directory = "netlify/functions"
